// <auto-generated />
using BitcoinBlazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitcoinBlazor.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200613114733_add bitcoin public key and network address types")]
    partial class addbitcoinpublickeyandnetworkaddresstypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitcoinBlazor.Data.DataModels.BitcoinAddresses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BitcoinPublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegacyBitcoinMainNetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegacyBitcoinTestNetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegWitBitcoinMainNetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegWitBitcoinTestNetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegWitP2SHBitcoinMainNetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegWitP2SHBitcoinTestNetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BitcoinAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
